name: Release
on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Test code
        run: npm run test

      - name: Build
        run: npm run build

      - name: Test code
        run: npm run test

      - name: Test dts
        run: npm run test:dts

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          branches: |
            [
              'master'
            ]
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
